name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  ci:
    name: Build + Test
    runs-on: macOS-latest

    strategy:
      matrix:
        api-level: [21, 29]

    steps:
    - uses: actions/checkout@v2

    - name: Build project
      run: fastlane assemble

    - name: Run unit tests
      run: fastlane unit_test

    - name: Run instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86
        disable-animations: true
        script: fastlane instrumentation_test
