name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  ci:
    name: Build + Test
    runs-on: macOS-latest

    strategy:
      matrix:
        api-level: [21, 29]

    steps:
    - uses: actions/checkout@v2

    - name: Generate cache key
      run: ./tools/checksum.sh checksum.txt

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/modules-2
        key: ${{ runner.os }}-gradlemodules-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlemodules-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/jars-3
        key: ${{ runner.os }}-gradlejars-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlejars-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches/build-cache-1
        key: ${{ runner.os }}-gradlebuildcache-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlebuildcache-

    - name: Build project
      run: fastlane assemble

    - name: Run unit tests
      run: fastlane unit_test

    # - name: Run instrumentation tests
    #   uses: reactivecircus/android-emulator-runner@v2
    #   with:
    #     api-level: ${{ matrix.api-level }}
    #     arch: x86
    #     disable-animations: true
    #     script: fastlane instrumentation_test
